vinosjiquilpan-main/src/pedidos/__init__.py
# El archivo __init__ realmente es constructor del módulo categorias
from flask import Blueprint

# Definir el Blueprint
pedido = Blueprint('pedido', __name__, url_prefix='/pedidos', template_folder='templates')

# Le estamos diciendo Blueprint que tiene rutas definidas
from . import routes

vinosjiquilpan-main/src/pedidos/routes.py
from flask import render_template, request

from . import pedido

varmongo= {"host": "localhost",
           "db": "vinos_jiquilpan",
           "port": 27017,
           "timeout": 1000,
           "user": "",
           "password": ""
           }

# Crear los endpoints
# Ruta: http://127.0.0.1:5000/productos
@pedido.route('/carrito')
def ver_carrito(): 

   
    return render_template('/pedidos/carrito.html')

@pedido.route('/checkout')
def verificar_cuenta():
    return 'desde cuenta...'



vinosjiquilpan-main/src/pedidos/templates/pedidos/carrito.html
{% extends "plantilla.html" %}

{% block slogan %}
<div class="row no-gutters slider-text align-items-center justify-content-center">
    <div class="col-md-9 ftco-animate mb-5 text-center">
        <p class="breadcrumbs mb-0"><span class="mr-2"><a href="{{url_for('index')}}">Inicio <i class="fa fa-chevron-right"></i></a></span> <span>Lista de Productos <i class="fa fa-chevron-right"></i></span></p>
      <h2 class="mb-0 bread" style="color: #fff;">Carrito</h2>
    </div>
</div>
{% endblock %}

{% block carrito %}
<section class="ftco-section">
    <div class="container">

        <div class="row">
          {% block mensajeCarrito %}
                <div class="col-md-12" id="mensaje">
                    {% for message in get_flashed_messages() %}
                      <div class="alert alert-danger">
                          <button type="button" class="close" data-dismiss="alert">&times;</button>
                          <a class="navbar-brand" href="{{url_for('login')}}">
                            <span>
                              {{ message }}
                            </span>
                          </a>
                      </div>
                    {% endfor %}
                    {# % block page_content %}{% endblock % #}
                </div>
          {% endblock %}
        </div>
        <div class="row">
            <div class="table-wrap">
                <table class="table">
                    <thead class="thead-primary">
                        <tr>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                            <th>Producto</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>Subtotal</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody id="contenido-carrito">
                        
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row justify-content-end">

            <div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
                <div class="cart-total mb-3">
                    <h3>Total del carrito</h3>
                    <p class="d-flex">
                        <span>Subtotal</span>
                        <span id="subtotal-orden">$0.00</span>
                    </p>
                    <p class="d-flex">
                        <span>Envio</span>
                        <span id="total-envio">$0.00</span>
                    </p>
                    <p class="d-flex">
                        <span>Descuento</span>
                        <span id="descuento-orden">$0.00</span>
                    </p>
                    <hr>
                    <p class="d-flex total-price">
                        <span>Total</span>
                        <span id="total-orden">$0.00</span>
                    </p>
                </div>
                <p class="text-center"><a href="{{url_for('pedido.verificar_cuenta')}}" class="btn btn-primary py-3 px-4 revisar-proceder">Revisar y Proceder</a></p>
                
                
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block pie %}
<footer class="ftco-footer">
    <div class="container">
<div class="row mb-5">
  <div class="col-sm-12 col-md">
    <div class="ftco-footer-widget mb-4">
      <h2 class="ftco-heading-2 logo"><a href="#">Liquor <span>Store</span></a></h2>
      <p>Far far away, behind the word mountains, far from the countries.</p>
      <ul class="ftco-footer-social list-unstyled mt-2">
        <li class="ftco-animate"><a href="#"><span class="fa fa-twitter"></span></a></li>
        <li class="ftco-animate"><a href="#"><span class="fa fa-facebook"></span></a></li>
        <li class="ftco-animate"><a href="#"><span class="fa fa-instagram"></span></a></li>
      </ul>
    </div>
  </div>
  <div class="col-sm-12 col-md">
    <div class="ftco-footer-widget mb-4 ml-md-4">
      <h2 class="ftco-heading-2">My Accounts</h2>
      <ul class="list-unstyled">
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>My Account</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Register</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Log In</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>My Order</a></li>
      </ul>
    </div>
  </div>
  <div class="col-sm-12 col-md">
    <div class="ftco-footer-widget mb-4 ml-md-4">
      <h2 class="ftco-heading-2">Information</h2>
      <ul class="list-unstyled">
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>About us</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Catalog</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Contact us</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Term &amp; Conditions</a></li>
      </ul>
    </div>
  </div>
  <div class="col-sm-12 col-md">
     <div class="ftco-footer-widget mb-4">
      <h2 class="ftco-heading-2">Quick Link</h2>
      <ul class="list-unstyled">
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>New User</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Help Center</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Report Spam</a></li>
        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Faq's</a></li>
      </ul>
    </div>
  </div>
  <div class="col-sm-12 col-md">
    <div class="ftco-footer-widget mb-4">
        <h2 class="ftco-heading-2">Have a Questions?</h2>
        <div class="block-23 mb-3">
          <ul>
            <li><span class="icon fa fa-map marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
            <li><a href="#"><span class="icon fa fa-phone"></span><span class="text">+2 392 3929 210</span></a></li>
            <li><a href="#"><span class="icon fa fa-paper-plane pr-4"></span><span class="text">info@yourdomain.com</span></a></li>
          </ul>
        </div>
    </div>
  </div>
</div>
</div>
<div class="container-fluid px-0 py-5 bg-black">
  <div class="container">
      <div class="row">
      <div class="col-md-12">

        <p class="mb-0" style="color: rgba(255,255,255,.5);"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </div>
</div>
</footer>
{% endblock %}

{% block misEscripts %}
    <script src="{{url_for('static', filename='js/js/appCarrito.js')}}"></script>
{% endblock %}

vinosjiquilpan-main/src/pedidos/templates/pedidos/checkout.html
{% extends "plantilla.html" %}

{% block slogan %}
<div class="row no-gutters slider-text align-items-center justify-content-center">
    <div class="col-md-9 ftco-animate mb-5 text-center">
        <p class="breadcrumbs mb-0"><span class="mr-2"><a href="{{url_for('index')}}">Inicio <i class="fa fa-chevron-right"></i></a></span> <span>Checkout <i class="fa fa-chevron-right"></i></span></p>
      <h2 class="mb-0 bread" style="color: #fff;">Revisar cuenta</h2>
    </div>
</div>
{% endblock %}

{% block caja %}
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
      <div class="col-xl-10 ftco-animate">
                    <form action="#" class="billing-form">
                        <h3 class="mb-4 billing-heading">Detalle de facturación</h3>
              <div class="row align-items-end">
                  <div class="col-md-6">
                <div class="form-group">
                    <label for="firstname">Nombre</label>
                  
                  {% if datosUsuario.nombre != None %}
                    <input type="text" class="form-control" placeholder="Nombre" id="nombre" value="{{datosUsuario.nombre}}">
                   {% else %}
                   <input type="text" class="form-control" placeholder="Nombre" id="nombre">
                  {% endif %}
                  
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                    <label for="lastname">Apellidos</label>
                  
                  {% if datosUsuario.apellidos != None %}
                  <input type="text" class="form-control" placeholder="Apellido Paterno Apellido Materno" id="apellidos" value="{{datosUsuario.apellidos}}">
                  {% else %}
                  <input type="text" class="form-control" placeholder="Apellido Paterno Apellido Materno" id="apellidos">
                  {% endif %}
                 
                </div>
            </div>
            <div class="w-100"></div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="country">Estado</label>
                        <div class="select-wrap">
                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                      <select name="estado" id="estado" class="form-control">
                          <option value="Michoacán">Michoacán</option>
                        <option value="Jalisco">Jalisco</option>
                        <option value="Guanajuato">Guanajuato</option>
                        <option value="San Luis Potosí">San Luis Potosí</option>
                        <option value="México">México</option>
                        <option value="Ciudad de México">Ciudad de México</option>
                      </select>
                    </div>
                    </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-6">
                    <div class="form-group">
                    <label for="streetaddress">Dirección</label>
                  
                  {% if datosUsuario.direccion != None %}
                    <input type="text" class="form-control" placeholder="Calle Número, Colonia, Ciudad, Estado" id="direccion" value="{{datosUsuario.direccion}}">
                  {% else %}
                     <input type="text" class="form-control" placeholder="Calle Número, Colonia, Ciudad, Estado" id="direccion">
                  {% endif %}
                  
                </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                  <input type="text" class="form-control" placeholder="Entre que calles">
                </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-6">
                    <div class="form-group">
                    <label for="towncity">Ciudad</label>
                  
                  {% if datosUsuario.ciudad != None %}
                    <input type="text" class="form-control" placeholder="Ciudad" id="ciudad" value="{{datosUsuario.ciudad}}">
                  {% else %} 
                    <input type="text" class="form-control" placeholder="Ciudad" id="ciudad">
                  {% endif %}
                  
                </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="postcodezip">Código Postal</label>
                  
                  {% if datosUsuario.codigopostal != None %}
                    <input type="text" class="form-control" placeholder="Código postal" id="codigo-postal" value="{{datosUsuario.codigopostal}}">
                  {% else %}
                    <input type="text" class="form-control" placeholder="Código postal" id="codigo-postal">
                  {% endif %}
                  
                </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-6">
                <div class="form-group">
                    <label for="phone">Teléfono</label>
                  
                  {% if datosUsuario.telefonoCasa != None %}
                     <input type="text" class="form-control" placeholder="Teléfono" id="telefono" value="{{datosUsuario.telefonoCasa}}">
                  {% else %}
                    <input type="text" class="form-control" placeholder="Teléfono" id="telefono">
                  {% endif %}
                  
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                    <label for="emailaddress">Correo Electrónico</label>
                 
                  {% if datosUsuario.correo != None %}
                    <input type="text" class="form-control" placeholder="Correo electrónico" id="correo-electronico" value="{{datosUsuario.correo}}" readonly>
                  {% else %}
                    <input type="text" class="form-control" placeholder="Correo electrónico" id="correo-electronico" readonly>
                  {% endif %}
                  
                </div>
            </div>
            <div class="w-100"></div>
            <div class="col-md-12">
                <div class="form-group mt-4">
                    <!-- Si desea considerar otras opciones -->
                </div>
            </div>
            </div>
          </form><!-- END -->



          <div class="row mt-5 pt-3 d-flex">
              <div class="col-md-6 d-flex">
                  <div class="cart-detail cart-total p-3 p-md-4">
                      <h3 class="billing-heading mb-4">Total del carrito</h3>
                      <p class="d-flex">
                                <span >Subtotal</span>
                                <span id="subtotal-orden">$0.00</span>
                            </p>
                            <p class="d-flex">
                                <span>Envio</span>
                                <span id="total-envio">$0.00</span>
                            </p>
                            <p class="d-flex">
                                <span>Descuento</span>
                                <span>$0.00</span>
                            </p>
                            <hr>
                            <p class="d-flex total-price">
                                <span>Total</span>
                                <span id="total-orden">$0.00</span>
                            </p>
                            </div>
              </div>
              <div class="col-md-6">
                  <div class="cart-detail p-3 p-md-4">
                      <h3 class="billing-heading mb-4">Método de pago</h3>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="radio">
                                           <label><input type="radio" name="optradio" class="mr-2" id="transferencia"> Transferencia bancaria</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="radio">
                                           <label><input type="radio" name="optradio" class="mr-2" id="oxxo"> OXXO </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="radio">
                                           <label><input type="radio" name="optradio" class="mr-2" id="paypal"> Paypal</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="checkbox">
                                           <label><input type="checkbox" value="" class="mr-2" id="terminosyCondiciones"> He leido y entendido los términos y condiciones y los acepto</label>
                                        </div>
                                    </div>
                                </div>
                                <p><a href="#"class="btn btn-primary py-3 px-4 realizar-pedido">Realizar el pedido</a></p>
                            </div>
              </div>
          </div>
      </div> <!-- .col-md-8 -->
    </div>
    </div>
</section>
{% endblock %}
{% block misEscripts %}
    <script src="{{url_for('static', filename='js/js/appCheckout.js')}}"></script>
{% endblock %}